### ISSUE TITLE
README references 'code.js' which has been updated to 'index.js' in code sample

### ISSUE THREAD

**Issue by jsbenning** [learn-co-curriculum/javascript-intro-to-mocha#11]
"In this case, it's figuring out where code.js lives."

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
