### ISSUE TITLE
possibly issue with node inspector instructions 

### ISSUE THREAD

**Issue by jenjiyi** [learn-co-curriculum/javascript-intro-to-mocha#3]
If working outside of IDE, running `npm run debug` doesn't work with current source code. 

I added this line under scripts in package.json:
`"debug": "node-debug --hidden node_modules _mocha --watch",` 

Not sure if this is the right method but it opened a new chrome window and produced debug link.

**Comment by aturkewi** [comment]
Removed use of this script from the readme. Thanks for raising the issue!
