### ISSUE TITLE
Array of paths to source files?

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/javascript-intro-to-mocha#5]
> ``` javascript
> ...
> 
>   jsdom.env(html, [], { src: babelResult.code }, (err, window) => {
>     if (err) {
>       return done(err);
>     }
> 
> ...
> ```
> 
> ...
> 
> Then we call `jsdom.env()`. This function receives four arguments:
> 1. ...
> 2. An **array of paths to source files**. We only have one file to test, so it's the only element in the
>    array.

I see an empty array, and I see a hash w/ a key of `src` and a value of what I believe is the compiled source code. Am I missing something, or is there no "array of paths to source files?"

**Comment by itzsaga** [comment]
Wondering about this too...?

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.
