### ISSUE TITLE
Problems with the debugger

### ISSUE THREAD

**Issue by Dom-Mc** [learn-co-curriculum/javascript-intro-to-mocha#7]
I was having issues with the debugger on node `v7.0.0`.  @pickledyamsman suggested downgrading to  `v6.3.1` and now it works fine.  It's probably worth mentioning in the lab.

**Comment by pickledyamsman** [comment]
@dom-mc do you by chance still have the error message that you were getting, that would help us add documentation so that we can help other students.

**Comment by Dom-Mc** [comment]
@pickledyamsman sorry but I wasn't able to recover it.  However I did a little bit of looking and found [this](https://github.com/node-inspector/node-inspector/issues/907#issue-172239159l).  Almost certain I was getting the same exact error (and solution).

**Comment by aturkewi** [comment]
Ended up removing use of the node inspector from the readme all together.
Thanks fro raising this!
